create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique check (order_number ~ '^[0-9]+$'),
  slices_margherita integer not null default 0 check (slices_margherita >= 0),
  slices_piccante integer not null default 0 check (slices_piccante >= 0),
  slices_marinara integer not null default 0 check (slices_marinara >= 0),
  status text not null default 'OPEN' check (status in ('OPEN', 'PROCESSED')),
  created_at timestamptz not null default now(),
  constraint orders_contain_slices check (
    slices_margherita + slices_piccante + slices_marinara > 0
  )
);

alter table public.orders enable row level security;

create policy "Authenticated users can read orders" on public.orders for select to authenticated using (true);
create policy "Authenticated users can create orders" on public.orders for insert to authenticated with check (true);
create policy "Authenticated users can update orders" on public.orders for update to authenticated using (true) with check (true);
create policy "Authenticated users can delete orders" on public.orders for delete to authenticated using (true);

create index if not exists orders_status_order_number_idx on public.orders (status, order_number);
